app = "telegrambot-ig0xgq"  # replace this with your Fly app name

[build]
  image = "docker.io/library/python:3.12-slim"

[env]
  # Bot token will be set as secret on Fly, so not here

[deploy]
  release_command = ""

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    port = 443
    
